## Logic Gates

### NOR Gate

In [1]:
import numpy as np 

def unitStep(v): 
    if v < 0: 
        return 1
    else: 
        return 0

def perceptronModel(x, w, b): 
    v = np.dot(w, x) + b 
    y = unitStep(v) 
    return y 

# NOR Logic Function 
# w1 = 1, w2 = 1, b = -1 
def NOR_logicFunction(x): 
    w = np.array([1, 1]) 
    b = -1
    return perceptronModel(x, w, b) 
 
test1 = np.array([0, 1])
test2 = np.array([1, 1])
test3 = np.array([0, 0])
test4 = np.array([1, 0])
print("NOR({}, {}) = {}".format(0, 1, NOR_logicFunction(test1))) 
print("NOR({}, {}) = {}".format(1, 1, NOR_logicFunction(test2))) 
print("NOR({}, {}) = {}".format(0, 0, NOR_logicFunction(test3))) 
print("NOR({}, {}) = {}".format(1, 0, NOR_logicFunction(test4))) 

NOR(0, 1) = 0
NOR(1, 1) = 0
NOR(0, 0) = 1
NOR(1, 0) = 0


### NAND Gate

In [2]:
def unitStep(v):
    if(v<=0):
        return 1
    else:
        return 0
    
def perceptronModel(x, w, b):
    v = np.dot(w, x) + b
    y = unitStep(v)
    return y

def NAND_logicFunction(x):
    w = np.array([1, 1])
    b = -1
    return perceptronModel(x, w, b)

test1 = np.array([1, 1])
test2 = np.array([0, 1])
test3 = np.array([1, 0])
test4 = np.array([0, 0])
print("NAND({}, {}) = {}".format(1, 1, NAND_logicFunction(test1)))
print("NAND({}, {}) = {}".format(0, 1, NAND_logicFunction(test2)))
print("NAND({}, {}) = {}".format(1, 0, NAND_logicFunction(test3)))
print("NAND({}, {}) = {}".format(0, 0, NAND_logicFunction(test4)))

NAND(1, 1) = 0
NAND(0, 1) = 1
NAND(1, 0) = 1
NAND(0, 0) = 1


### XOR Gate

In [3]:
def unitStep(v):
    if(v==0):
        return 1
    else:
        return 0
    
def perceptronModel(x, w, b):
    v = np.dot(w, x) + b
    y = unitStep(v)
    return y

def XOR_logicFunction(x):
    w = np.array([1, 1])
    b = -1
    return perceptronModel(x, w, b)

test1 = np.array([1, 1])
test2 = np.array([0, 1])
test3 = np.array([1, 0])
test4 = np.array([0, 0])
print("XOR({}, {}) = {}".format(1, 1, XOR_logicFunction(test1)))
print("XOR({}, {}) = {}".format(0, 1, XOR_logicFunction(test2)))
print("XOR({}, {}) = {}".format(1, 0, XOR_logicFunction(test3)))
print("XOR({}, {}) = {}".format(0, 0, XOR_logicFunction(test4)))

XOR(1, 1) = 0
XOR(0, 1) = 1
XOR(1, 0) = 1
XOR(0, 0) = 0


### AND Gate

In [4]:
import numpy as np 

def unitStep(v): 
    if v >= 0: 
        return 1
    else: 
        return 0

def perceptronModel(x, w, b): 
    v = np.dot(w, x) + b 
    y = unitStep(v) 
    return y 

# AND Logic Function 
# w1 = 1, w2 = 1, b = -1.5 
def AND_logicFunction(x): 
    w = np.array([1, 1]) 
    b = -1.5
    return perceptronModel(x, w, b) 
 
test1 = np.array([0, 1]) 
test2 = np.array([1, 1]) 
test3 = np.array([0, 0]) 
test4 = np.array([1, 0]) 

print("AND({}, {}) = {}".format(0, 1, AND_logicFunction(test1))) 
print("AND({}, {}) = {}".format(1, 1, AND_logicFunction(test2))) 
print("AND({}, {}) = {}".format(0, 0, AND_logicFunction(test3))) 
print("AND({}, {}) = {}".format(1, 0, AND_logicFunction(test4))) 

AND(0, 1) = 0
AND(1, 1) = 1
AND(0, 0) = 0
AND(1, 0) = 0


### OR Gate

In [5]:
import numpy as np 

def unitStep(v): 
    if v >= 0: 
        return 1
    else: 
        return 0

def perceptronModel(x, w, b): 
    v = np.dot(w, x) + b 
    y = unitStep(v) 
    return y 

def OR_logicFunction(x): 
    w = np.array([1, 1]) 
    b = -1
    return perceptronModel(x, w, b) 
 
test1 = np.array([0, 1])
test2 = np.array([1, 1])
test3 = np.array([0, 0])
test4 = np.array([1, 0])
print("OR({}, {}) = {}".format(0, 1, OR_logicFunction(test1))) 
print("OR({}, {}) = {}".format(1, 1, OR_logicFunction(test2))) 
print("OR({}, {}) = {}".format(0, 0, OR_logicFunction(test3))) 
print("OR({}, {}) = {}".format(1, 0, OR_logicFunction(test4))) 

OR(0, 1) = 1
OR(1, 1) = 1
OR(0, 0) = 0
OR(1, 0) = 1


### NOT Gate

In [6]:
def unitStep(v):
    if(v<0):
        return 1
    else:
        return 0
    
def perceptronModel(x, w, b):
    v = np.dot(w, x) + b
    y = unitStep(v)
    return y

def NOT_logicFunction(x):
    w = np.array([1])
    b = -1
    return perceptronModel(x, w, b)

test1 = np.array([1])
test2 = np.array([0])
print("NOT({}) = {}".format(1, NOT_logicFunction(test1)))
print("NOT({}) = {}".format(0, NOT_logicFunction(test2)))

NOT(1) = 0
NOT(0) = 1


### Binary Classification 1

In [7]:
points = {'P0': np.array([-1, -1, -1]), 'P1': np.array([-1, -1, 1]), 'P2': np.array([-1, 1, -1]),
          'P3':np.array([-1, 1, 1]), 'P4': np.array([1, -1, -1]), 'P5': np.array([1, -1, 1]),
          'P6': np.array([1, 1, -1]), 'P7': np.array([1, 1, 1])}

In [8]:
C1 = ['P7']
C2 =['P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6']

weights = np.zeros(len(points['P0']))
bias = 0
print(weights)

[0. 0. 0.]


In [9]:
C1 = ['P7']
C2 =['P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6']

weights = np.zeros(len(points['P7']))
bias = 0
print(weights)

[0. 0. 0.]


In [10]:
learning_rate = 1
epochs = 1000

In [11]:
for epoch in range(epochs):
    for point in C2:
        x = points[point]
        y = 1
        
        summation = np.dot(weights, x) + bias
        
        if summation<=0:
            weights += learning_rate * x
            bias += learning_rate

In [12]:
weights

array([-1., -1., -1.])

In [13]:
bias

3

In [14]:
new_point = np.array([1, 1, 1])
summation = np.dot(weights, new_point) + bias

In [15]:
if(summation>0):
    print(f'The new point {new_point} belongs to class C2')
else:
     print(f'The new point {new_point} belongs to class C1')

The new point [1 1 1] belongs to class C1


In [16]:
new_point = np.array([1, -1, 1])
summation = np.dot(weights, new_point) + bias

In [17]:
if(summation>0):
    print(f'The new point {new_point} belongs to class C2')
else:
     print(f'The new point {new_point} belongs to class C1')

The new point [ 1 -1  1] belongs to class C2


### Binary Classification 2

In [18]:
def is_linearly_separable(points1):
    labels = [1, 1, 1, 1, -1, -1, -1, -1]
    weights = np.zeros(len(points1[0]))
    print(weights)

    for _ in range(1000):
        misclassified = False

        for i, point in enumerate(points1):
            if np.dot(point, weights) * labels[i] <= 0:
                weights += labels[i] * point
                misclassified = True
                print(weights)

        if not misclassified:
            return True

points1 = [np.array([-1, -1, -1]), np.array([-1, -1, 1]), np.array([-1, 1, -1]),
           np.array([-1, 1, 1]), np.array([1, -1, -1]), np.array([1, -1, 1]),
          np.array([1, 1, -1]), np.array([1, 1, 1])]

if is_linearly_separable(points1):
    print("The binary classification problem is linearly separable.")
else:
    print("The binary classification problem is not linearly separable.")


[0. 0. 0.]
[-1. -1. -1.]
[-2.  0.  0.]
The binary classification problem is linearly separable.
